wallpaper {
	monitor = HDMI-A-1
	path = ~/wallpaper/wallhaven-rq75r7.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-2
	path = ~/wallpaper/wallhaven-rq75r7.jpg

	fit_mode = cover
}

splash = false
