" Generated by worldwall-theme-watch; local edits are overwritten.
highlight clear
if exists("syntax_on")
  syntax reset
endif
set background=dark
let g:colors_name = "worldwall"

highlight Normal guifg=#d1d4e2 guibg=#10161a ctermfg=254 ctermbg=0
highlight NormalNC guifg=#d1d4e2 guibg=#10161a ctermfg=254 ctermbg=0
highlight NormalFloat guifg=#d1d4e2 guibg=#283034 ctermfg=254 ctermbg=0
highlight Comment guifg=#8c9098 ctermfg=8 gui=italic cterm=italic
highlight Constant guifg=#58b4b8 ctermfg=14
highlight String guifg=#98971a ctermfg=2
highlight Character guifg=#98971a ctermfg=2
highlight Number guifg=#d79921 ctermfg=3
highlight Boolean guifg=#d79921 ctermfg=3
highlight Float guifg=#d79921 ctermfg=3
highlight Identifier guifg=#84a498 ctermfg=4
highlight Function guifg=#18969d ctermfg=6
highlight Statement guifg=#18969d ctermfg=6 gui=bold cterm=bold
highlight Conditional guifg=#18969d ctermfg=6
highlight Repeat guifg=#18969d ctermfg=6
highlight Operator guifg=#d1d4e2 ctermfg=254
highlight PreProc guifg=#84a498 ctermfg=4
highlight Type guifg=#84a498 ctermfg=4
highlight Special guifg=#58b4b8 ctermfg=14
highlight Underlined guifg=#18969d ctermfg=6 gui=underline cterm=underline
highlight Todo guifg=#d1d4e2 guibg=#485c58 ctermfg=0 ctermbg=4 gui=bold cterm=bold
highlight Directory guifg=#84a498 ctermfg=4
highlight Title guifg=#18969d ctermfg=6 gui=bold cterm=bold
highlight LineNr guifg=#8c9098 guibg=#10161a ctermfg=8 ctermbg=0
highlight CursorLineNr guifg=#18969d guibg=#243030 ctermfg=6 ctermbg=0 gui=bold cterm=bold
highlight CursorLine guibg=#243030 ctermbg=0
highlight CursorColumn guibg=#243030 ctermbg=0
highlight ColorColumn guibg=#243030 ctermbg=0
highlight Cursor guifg=#d1d4e2 guibg=#102428 ctermfg=0 ctermbg=4
highlight lCursor guifg=#d1d4e2 guibg=#102428 ctermfg=0 ctermbg=4
highlight MatchParen guifg=#58b4b8 guibg=#485c58 ctermfg=14 ctermbg=4 gui=bold cterm=bold
highlight Visual guifg=#d1d4e2 guibg=#485c58 ctermfg=254 ctermbg=4
highlight Search guifg=#d1d4e2 guibg=#202828 ctermfg=0 ctermbg=4 gui=bold cterm=bold
highlight IncSearch guifg=#d1d4e2 guibg=#103038 ctermfg=0 ctermbg=4 gui=bold cterm=bold
highlight CurSearch guifg=#d1d4e2 guibg=#103038 ctermfg=0 ctermbg=4 gui=bold cterm=bold
highlight StatusLine guifg=#d1d4e2 guibg=#344440 ctermfg=254 ctermbg=4 gui=bold cterm=bold
highlight StatusLineNC guifg=#8c9098 guibg=#10161a ctermfg=8 ctermbg=0
highlight TabLine guifg=#8c9098 guibg=#344440 ctermfg=8 ctermbg=4
highlight TabLineSel guifg=#d1d4e2 guibg=#103038 ctermfg=7 ctermbg=4 gui=bold cterm=bold
highlight TabLineFill guifg=#8c9098 guibg=#10161a ctermfg=8 ctermbg=0
highlight VertSplit guifg=#098b92 guibg=#10161a ctermfg=6 ctermbg=0
highlight WinSeparator guifg=#098b92 guibg=#10161a ctermfg=6 ctermbg=0
highlight Pmenu guifg=#d1d4e2 guibg=#283034 ctermfg=254 ctermbg=4
highlight PmenuSel guifg=#d1d4e2 guibg=#485c58 ctermfg=7 ctermbg=4 gui=bold cterm=bold
highlight PmenuSbar guibg=#344440 ctermbg=4
highlight PmenuThumb guibg=#18969d ctermbg=6
highlight Folded guifg=#8c9098 guibg=#283034 ctermfg=8 ctermbg=4
highlight FoldColumn guifg=#8c9098 guibg=#10161a ctermfg=8 ctermbg=0
highlight SignColumn guifg=#d1d4e2 guibg=#10161a ctermfg=254 ctermbg=0
highlight NonText guifg=#8c9098 guibg=#10161a ctermfg=8 ctermbg=0
highlight Whitespace guifg=#8c9098 guibg=#10161a ctermfg=8 ctermbg=0
highlight SpecialKey guifg=#84a498 guibg=#10161a ctermfg=4 ctermbg=0
highlight Error guifg=#fb4934 guibg=#10161a ctermfg=9 ctermbg=0 gui=bold,undercurl cterm=bold,undercurl
highlight ErrorMsg guifg=#fb4934 guibg=#10161a ctermfg=9 ctermbg=0 gui=bold cterm=bold
highlight WarningMsg guifg=#fabd2f guibg=#10161a ctermfg=11 ctermbg=0 gui=bold cterm=bold
highlight MoreMsg guifg=#18969d guibg=#10161a ctermfg=6 ctermbg=0 gui=bold cterm=bold
highlight ModeMsg guifg=#84a498 guibg=#10161a ctermfg=4 ctermbg=0 gui=bold cterm=bold
highlight DiffAdd guifg=#b8bb26 guibg=#10161a ctermfg=10 ctermbg=0
highlight DiffChange guifg=#fabd2f guibg=#10161a ctermfg=11 ctermbg=0
highlight DiffDelete guifg=#fb4934 guibg=#10161a ctermfg=9 ctermbg=0
highlight DiffText guifg=#d1d4e2 guibg=#485c58 ctermfg=254 ctermbg=4 gui=bold cterm=bold
highlight DiagnosticError guifg=#fb4934 ctermfg=9
highlight DiagnosticWarn guifg=#fabd2f ctermfg=11
highlight DiagnosticInfo guifg=#84a498 ctermfg=4
highlight DiagnosticHint guifg=#18969d ctermfg=6
